### ISSUE TITLE
Intel Arc b580 gpu not detected after Jan v.6xx

### ISSUE THREAD

**Issue by taniscott** [menloresearch/jan#5551]
Hi,

My B580 GPU is no longer detected by Jan since v6.xx if I downgrade to v5.17 is shows up again.

I can manually change  the .janrc setting

 llamacppVariant: win-avx-x64 to
llamacppVariant: win-vulkan-x64

to get vulkan to run with with my B580 but it's only a temp fix since the .janrc file is reset on restart or when changing models.

I've scoured my pc of old jan files and settings and currently have a fresh copy of v6.03 installed.

![Image](https://github.com/user-attachments/assets/a0d9d2e1-afd6-4ea3-be70-44e71b8665cf)

I have two other PC's with Nvidia cards and 6.03 works fine on them.

Thanks

Chris

**Comment by samschurter** [comment]
Not sure whether to chime in on this bug or #5006 , Figured I'd go with here since this one is still open. I have a dual A770 setup that works fine with llama.cpp + Vulkan in LM Studio, but Jan is not recognizing either card. The trick with setting `llamacppVariant` doesn't work either, I change that setting in the file and load Jan and it still sends the model directly to system RAM. I have tried both the stable channel and the nightly release (v0.6.4-674) 

I'm running Windows 10 with an AMD Ryzen 1920X if that helps. My Intel Arc drivers are also completely up to date.

**Comment by samschurter** [comment]
Update: I tried changing the `llamacppVariant` _after_ starting Jan, but _before_ loading a model, and that worked to get it to push the model to the GPUs. That does only work temporarily though.

**Comment by D0wn10ad** [comment]
hi, i went the extreme to just replace win-avx-x74 with the content of win-vulkan-x64 in %APPDATA% and it is now working, but i guess will not survive any update. (reported my case as comment in #5960 )

**Comment by taniscott** [comment]
With the release of 0.6.6 the problem seems to be fixed on my machine. I'm now pulling 32+ tokens with 8B Deepseek R1  instead of 4 to 7 tokens before the fix. Thanks

**Comment by samschurter** [comment]
This is also resolved for me in v0.6.6

**Comment by LazyYuuki** [comment]
Closed as resolved
Thanks everyone for your report!
